Repository puppygirlzone/webfishing-bans, pull requests merged in 2024-11, with the labels that each got.

#3 Autorelease again
  .github/auto-release.yaml
  .github/workflows/release-now.yaml
  no.md
Labels: minor

#4 Update LobbyLifeguard.json
  LobbyLifeguard.json
Labels: patch

#6 New webfishing airlines alt
  LobbyLifeguard.json
Labels: patch

#8 Fixed workflow and .gitattributes
  .gitattributes
  .github/workflows/release-now.yaml
Labels: minor

#9 New Grincher's Club Members
  LobbyLifeguard.json
  wall-of-shame.md
Labels: minor

#10 Update LobbyLifeguard.json
  LobbyLifeguard.json
Labels: patch, removal

#11 New users popped up in fanclub
  LobbyLifeguard.json
  wall-of-shame.md
Labels: minor

#12 Removed 76561198838632747
  LobbyLifeguard.json
Labels: patch

#13 Added 76561199803516629
  LobbyLifeguard.json
Labels: patch
