Repository puppygirlzone/webfishing-bans, pull requests merged in 2024-12, with the labels that each got.

#14 Removal of 76561198002149202
  LobbyLifeguard.json
  wall-of-shame.md
Labels: patch

#15 Another Grincher follower added
  LobbyLifeguard.json
  wall-of-shame.md
Labels: patch

#16 Update LobbyLifeguard.json
  LobbyLifeguard.json
Labels: patch

#17 Added 76561199805766631, removed duplicate for 76561198068059056
  LobbyLifeguard.json
  wall-of-shame.md
Labels: patch, added

#18 Update LobbyLifeguard.json
  LobbyLifeguard.json
Labels: patch, removal

#20 Combined Fluffy's list into this one
  LobbyLifeguard.json
  wall-of-shame.md
Labels: patch, added

#22 Fixing cache not working?
  .github/workflows/html.yaml
  .github/workflows/shamemd.yaml
Labels: NoRelease

#23 Update LobbyLifeguard.json
  LobbyLifeguard.json
Labels: NoRelease, added

#25 Removed 76561198213436231 and 76561198071921317
  LobbyLifeguard.json
Labels: patch, removal

#26 Attempting to fix a issue with WOS updater
  .github/workflows/html.yaml
  .github/workflows/shamemd.yaml
Labels: NoRelease

#27 Forgot to change the branch is pushes to smh
  .github/workflows/html.yaml
Labels: NoRelease

#28 Wrong file pattern
  .github/workflows/html.yaml
Labels: NoRelease

#29 Changes yippee
  .github/workflows/html.yaml
Labels: NoRelease

#30 Final test
  .github/workflows/html.yaml
Labels: NoRelease

#31 Feature/auto shame
  .github/workflows/html.yaml
  build/shame.html
  wall-of-shame.md
Labels: NoRelease

#32 Congrats on tonights biggest Whiner
  LobbyLifeguard.json
Labels: patch

#33 Added 76561198057221376 for troll drawing
  LobbyLifeguard.json
Labels: patch

#34 Added 76561198079974374 and 76561198955816367
  LobbyLifeguard.json
Labels: patch

#36 Removed 76561199373597469
  LobbyLifeguard.json
Labels: patch

#37 Added 76561199802241667
  LobbyLifeguard.json
Labels: patch

#38 Added 76561199366645932 and 76561198450291876
  LobbyLifeguard.json
Labels: patch, added

#39 Added another one of the discord link spammers
  LobbyLifeguard.json
Labels: patch, added

#40 Removed/re-added
  LobbyLifeguard.json
Labels: patch

#41 Removed 76561199168249782
  LobbyLifeguard.json
Labels: patch, removal

#43 removed 76561198846532050
  LobbyLifeguard.json
Labels: patch, removal

#44 Added another ATC account
  LobbyLifeguard.json
Labels: patch

#46 Added 76561199807575343
  LobbyLifeguard.json
Labels: patch, added

#47 Added 76561199807263177
  LobbyLifeguard.json
Labels: minor, added

#48 Added 76561199806806969
  LobbyLifeguard.json
Labels: patch, added

#51 Updated README to combat against botting service
  README.md
Labels: NoRelease

#52 Updated again
  README.md
Labels: NoRelease

#53 add 76561197960723152
  LobbyLifeguard.json
Labels: patch, added

#55 Added 76561199805669685
  LobbyLifeguard.json
Labels: patch, added

#56 Added 76561198123893056 and 76561199192216807
  LobbyLifeguard.json
Labels: patch, added

#57 Added 76561199427143677
  LobbyLifeguard.json
  evidence/76561199427143677/2.png
  evidence/76561199427143677/image.png
Labels: patch, added

#58 Added 76561199353296118
  LobbyLifeguard.json
Labels: patch, added

#59 Removed 76561199353296118
  LobbyLifeguard.json
Labels: patch, removal

#60 Added 76561199791402777
  LobbyLifeguard.json
Labels: patch, added

#61 Added 76561199476030587
  LobbyLifeguard.json
Labels: patch, added

#62 Added 76561199518881252
  LobbyLifeguard.json
Labels: patch, added

#63 Added 76561199223138820
  LobbyLifeguard.json
Labels: patch, added

#65 Added 76561199812719861
  LobbyLifeguard.json
Labels: patch, added
